language: python
python: 
  - "3.8"
# command to install dependencies
install:
  - pip install pylint
  - pip install flask
  - pip install flask_restful
  - pip install flask_cors
  - pip install pandas
  - pip install pillow
  - pip install scikit-learn
  - pip install matplotlib
  - pip install requests
  - pip install keras
# command to run tests
script:
  - pylint --rcfile=.pylintrc ml/train.py
  - pylint --rcfile=.pylintrc backend/main.py
